// GENERATED by scripts/build-icons.mjs — DO NOT EDIT. Curated from Lucide (ISC).
import { forwardRef } from 'react';
import { Icon } from './Icon';
import type { IconProps } from './Icon';

type NamedIconProps = Omit<IconProps, 'name'>;

export const IconArchive = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconArchive(props, ref) {
    return <Icon ref={ref} name="archive" {...props} />;
  },
);
export const IconArrowUpRight = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconArrowUpRight(props, ref) {
    return <Icon ref={ref} name="arrow-up-right" {...props} />;
  },
);
export const IconBell = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconBell(props, ref) {
    return <Icon ref={ref} name="bell" {...props} />;
  },
);
export const IconBook = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconBook(props, ref) {
    return <Icon ref={ref} name="book" {...props} />;
  },
);
export const IconCalendar = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconCalendar(props, ref) {
    return <Icon ref={ref} name="calendar" {...props} />;
  },
);
export const IconCheck = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconCheck(props, ref) {
    return <Icon ref={ref} name="check" {...props} />;
  },
);
export const IconChevronDown = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconChevronDown(props, ref) {
    return <Icon ref={ref} name="chevron-down" {...props} />;
  },
);
export const IconChevronLeft = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconChevronLeft(props, ref) {
    return <Icon ref={ref} name="chevron-left" {...props} />;
  },
);
export const IconChevronRight = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconChevronRight(props, ref) {
    return <Icon ref={ref} name="chevron-right" {...props} />;
  },
);
export const IconChevronUp = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconChevronUp(props, ref) {
    return <Icon ref={ref} name="chevron-up" {...props} />;
  },
);
export const IconCircle = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconCircle(props, ref) {
    return <Icon ref={ref} name="circle" {...props} />;
  },
);
export const IconClock = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconClock(props, ref) {
    return <Icon ref={ref} name="clock" {...props} />;
  },
);
export const IconCommand = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconCommand(props, ref) {
    return <Icon ref={ref} name="command" {...props} />;
  },
);
export const IconDotsHorizontal = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconDotsHorizontal(props, ref) {
    return <Icon ref={ref} name="dots-horizontal" {...props} />;
  },
);
export const IconDownload = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconDownload(props, ref) {
    return <Icon ref={ref} name="download" {...props} />;
  },
);
export const IconEyeOff = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconEyeOff(props, ref) {
    return <Icon ref={ref} name="eye-off" {...props} />;
  },
);
export const IconFlag = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconFlag(props, ref) {
    return <Icon ref={ref} name="flag" {...props} />;
  },
);
export const IconFolder = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconFolder(props, ref) {
    return <Icon ref={ref} name="folder" {...props} />;
  },
);
export const IconGear = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconGear(props, ref) {
    return <Icon ref={ref} name="gear" {...props} />;
  },
);
export const IconGrid = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconGrid(props, ref) {
    return <Icon ref={ref} name="grid" {...props} />;
  },
);
export const IconInbox = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconInbox(props, ref) {
    return <Icon ref={ref} name="inbox" {...props} />;
  },
);
export const IconJournal = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconJournal(props, ref) {
    return <Icon ref={ref} name="journal" {...props} />;
  },
);
export const IconKey = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconKey(props, ref) {
    return <Icon ref={ref} name="key" {...props} />;
  },
);
export const IconLayers = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconLayers(props, ref) {
    return <Icon ref={ref} name="layers" {...props} />;
  },
);
export const IconLink = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconLink(props, ref) {
    return <Icon ref={ref} name="link" {...props} />;
  },
);
export const IconLock = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconLock(props, ref) {
    return <Icon ref={ref} name="lock" {...props} />;
  },
);
export const IconMonitor = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconMonitor(props, ref) {
    return <Icon ref={ref} name="monitor" {...props} />;
  },
);
export const IconMoon = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconMoon(props, ref) {
    return <Icon ref={ref} name="moon" {...props} />;
  },
);
export const IconNote = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconNote(props, ref) {
    return <Icon ref={ref} name="note" {...props} />;
  },
);
export const IconPen = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconPen(props, ref) {
    return <Icon ref={ref} name="pen" {...props} />;
  },
);
export const IconPerson = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconPerson(props, ref) {
    return <Icon ref={ref} name="person" {...props} />;
  },
);
export const IconPlus = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconPlus(props, ref) {
    return <Icon ref={ref} name="plus" {...props} />;
  },
);
export const IconPuzzle = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconPuzzle(props, ref) {
    return <Icon ref={ref} name="puzzle" {...props} />;
  },
);
export const IconRepeat = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconRepeat(props, ref) {
    return <Icon ref={ref} name="repeat" {...props} />;
  },
);
export const IconSearch = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconSearch(props, ref) {
    return <Icon ref={ref} name="search" {...props} />;
  },
);
export const IconShield = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconShield(props, ref) {
    return <Icon ref={ref} name="shield" {...props} />;
  },
);
export const IconSparkle = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconSparkle(props, ref) {
    return <Icon ref={ref} name="sparkle" {...props} />;
  },
);
export const IconSun = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconSun(props, ref) {
    return <Icon ref={ref} name="sun" {...props} />;
  },
);
export const IconTag = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconTag(props, ref) {
    return <Icon ref={ref} name="tag" {...props} />;
  },
);
export const IconTimer = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconTimer(props, ref) {
    return <Icon ref={ref} name="timer" {...props} />;
  },
);
export const IconTrash = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconTrash(props, ref) {
    return <Icon ref={ref} name="trash" {...props} />;
  },
);
export const IconUnlock = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconUnlock(props, ref) {
    return <Icon ref={ref} name="unlock" {...props} />;
  },
);
export const IconUpload = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconUpload(props, ref) {
    return <Icon ref={ref} name="upload" {...props} />;
  },
);
export const IconUsers = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconUsers(props, ref) {
    return <Icon ref={ref} name="users" {...props} />;
  },
);
export const IconX = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconX(props, ref) {
    return <Icon ref={ref} name="x" {...props} />;
  },
);
export const IconZap = forwardRef<SVGSVGElement, NamedIconProps>(
  function IconZap(props, ref) {
    return <Icon ref={ref} name="zap" {...props} />;
  },
);
