#!/usr/bin/env node
/*
 * Icon curation pipeline (roadmap Phase 0 decision, executed in Phase 1).
 *
 * Source: Lucide (ISC license) via the lucide-static devDependency — dev-time
 * vendoring only, the published package carries no icon dependency. Glyphs are
 * renamed to plain Ornie nouns where Lucide's name is jargon (D-40), and the
 * Icon component locks stroke 1.9 / round caps / round joins at render time.
 *
 * Emits:
 *   src/primitives/Icon/glyphs.generated.ts   name → inner-SVG markup + IconName union
 *   src/primitives/Icon/icons.generated.tsx   individual <IconCheck /> exports (tree-shakeable)
 *
 * Run: pnpm icons   (after changing the GLYPHS map below)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const lucideDir = join(root, 'node_modules/lucide-static/icons');

// ornie name → lucide file. Plain daily nouns only (D-40).
const GLYPHS = {
  check: 'check',
  circle: 'circle',
  plus: 'plus',
  sparkle: 'sparkle', // Ask
  inbox: 'inbox',
  sun: 'sun', // today
  calendar: 'calendar', // upcoming
  layers: 'layers', // anytime
  archive: 'archive', // someday
  book: 'book', // logbook
  trash: 'trash-2',
  folder: 'folder', // project
  note: 'sticky-note',
  pen: 'pen',
  journal: 'notebook-pen',
  repeat: 'repeat', // habits
  person: 'user',
  users: 'users',
  gear: 'settings',
  lock: 'lock',
  unlock: 'lock-open',
  key: 'key',
  shield: 'shield',
  search: 'search',
  command: 'command',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'chevron-down': 'chevron-down',
  'arrow-up-right': 'arrow-up-right',
  'dots-horizontal': 'ellipsis',
  x: 'x',
  clock: 'clock',
  bell: 'bell',
  zap: 'zap', // energy
  tag: 'tag',
  link: 'link', // wikilink
  grid: 'layout-grid', // pages
  puzzle: 'puzzle', // modules
  download: 'download', // export
  upload: 'upload', // import
  'eye-off': 'eye-off',
  moon: 'moon',
  monitor: 'monitor',
  timer: 'timer',
  flag: 'flag',
};

const inner = (svg) =>
  svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*/, '')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim();

const pascal = (name) => name.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());

const names = Object.keys(GLYPHS).sort();
const glyphEntries = names.map((n) => {
  const svg = readFileSync(join(lucideDir, `${GLYPHS[n]}.svg`), 'utf8');
  return `  '${n}': '${inner(svg).replace(/'/g, "\\'")}',`;
});

writeFileSync(
  join(root, 'src/primitives/Icon/glyphs.generated.ts'),
  `// GENERATED by scripts/build-icons.mjs — DO NOT EDIT. Curated from Lucide (ISC).
// Renames to plain Ornie nouns happen in the GLYPHS map in that script (D-40).

export type IconName =
${names.map((n) => `  | '${n}'`).join('\n')};

export const glyphs: Record<IconName, string> = {
${glyphEntries.join('\n')}
};
`,
);

writeFileSync(
  join(root, 'src/primitives/Icon/icons.generated.tsx'),
  `// GENERATED by scripts/build-icons.mjs — DO NOT EDIT. Curated from Lucide (ISC).
import { forwardRef } from 'react';
import { Icon } from './Icon';
import type { IconProps } from './Icon';

type NamedIconProps = Omit<IconProps, 'name'>;

${names
  .map(
    (n) => `export const Icon${pascal(n)} = forwardRef<SVGSVGElement, NamedIconProps>(
  function Icon${pascal(n)}(props, ref) {
    return <Icon ref={ref} name="${n}" {...props} />;
  },
);`,
  )
  .join('\n')}
`,
);

console.log(`${names.length} glyphs → src/primitives/Icon/{glyphs,icons}.generated`);
